name: deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Elasticsearch ${{ github.ref_name }} Sql Plugin
#          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          body:
            '
            ```
            1.  parse sql into elasticsearch dsl

            2.  query dataset with sql
            ```
            '
          files: |
            isql-plugin/target/elasticsearch-sql-plugin.zip
